### ISSUE TITLE
CI/CD Test on PR

### ISSUE THREAD

**Issue by rickyxyz** [rickyxyz/circle-circle#4]
TODO:

- [ ] Refactor tests so it can run without setup data
- [ ] Run test on PR
- [ ] Automated Firestore rule deployment on merge
- [ ] Setup staging env for Firebase (probably need to make new Firebase project)

Obstacle:
- ~~`firebase emulators:exec "playwright test"` does not run~~
- How to make multiple Firestore environment?
- How to make test able to run on all environment?
- How to workaround Vercel's deployment protection?

Idea:
- ~~Use npx kill-port to kill Firebase port after e2e test~~
